# Generated by Django 4.0.5 on 2022-07-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetic_form', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_form', models.CharField(max_length=100)),
                ('orthography_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LexicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(choices=[('noun', 'noun'), ('proper noun', 'proper noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('conjunction', 'conjunction'), ('preposition', 'preposition'), ('pronoun', 'pronoun'), ('interjection', 'interjection'), ('numeral', 'numeral'), ('particle', 'particle'), ('other', 'other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_number', models.IntegerField()),
                ('lexical_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexicalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.form')),
            ],
            bases=('dictionary.form',),
        ),
        migrations.CreateModel(
            name='SenseAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('senses', models.ManyToManyField(to='dictionary.sense')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexical_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexicalentry')),
            ],
        ),
        migrations.AddField(
            model_name='lexicalentry',
            name='lexicon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexicon'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_representation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.formrepresentation'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_number', models.IntegerField()),
                ('lexical_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexicalentry')),
                ('list_of_components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.listofcomponents')),
            ],
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.form')),
                ('grammatical_number', models.CharField(blank=True, choices=[('singular', 'singular'), ('plural', 'plural'), ('dual', 'dual'), ('collective', 'collective')], max_length=25)),
                ('grammatical_gender', models.CharField(blank=True, choices=[('masculine', 'masculine'), ('feminine', 'feminine'), ('neutral', 'neutral')], max_length=25)),
                ('grammatical_tense', models.CharField(blank=True, choices=[('present', 'present'), ('imperfect', 'imperfect'), ('past', 'past'), ('future', 'future')], max_length=25)),
                ('grammatical_mood', models.CharField(blank=True, choices=[('indicative', 'indicative'), ('conjunctive', 'conjunctive'), ('conditional', 'conditional'), ('participle', 'participle'), ('subjunctive', 'subjunctive'), ('imperative', 'imperative'), ('infinitive', 'infinitive')], max_length=25)),
                ('person', models.CharField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('third', 'third')], max_length=25)),
                ('lexical_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.lexicalentry')),
            ],
            bases=('dictionary.form',),
        ),
        migrations.AddField(
            model_name='lexicalentry',
            name='lemma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.lemma'),
        ),
    ]
