# Generated by Django 4.0.5 on 2022-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senseaxis',
            name='senses',
        ),
        migrations.AddField(
            model_name='sense',
            name='sense_axiss',
            field=models.ManyToManyField(blank=True, to='dictionary.senseaxis'),
        ),
        migrations.AlterField(
            model_name='senseaxis',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
